# Generated by Django 5.2.6 on 2026-01-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='applicant_lawyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='applicant_lawyer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='respondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='respondent_lawyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='respondent_lawyer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
