# Generated by Django 5.2.6 on 2026-01-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_netfamilyproperty13b_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netfamilypropertystatement',
            name='draft',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
