# Generated by Django 5.2.6 on 2026-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_comparison_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonnetfamilyproperty',
            name='draft',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='business_name_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='employer_name_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='is_self_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='is_unemployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='my_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='my_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='unemployed_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
