# Generated by Django 5.2.6 on 2026-01-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_comparisonnetfamilyproperty_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='has_children_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='household_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='household_contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='household_contribution_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='lives_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='lives_with_other_adults',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='living_with_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='living_with_someone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='number_of_children_in_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_adults_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_does_not_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_earns_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_income_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_no_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='spouse_works',
            field=models.BooleanField(default=False),
        ),
    ]
