# Generated by Django 5.2.6 on 2026-01-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_financialstatement_has_children_in_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='alcohol_tobacco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='applicant_fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='applicant_lawyer_fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='automatic_deductions_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='babysitting_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='bank_accounts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_details_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_details_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_details_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_details_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_item_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_item_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_item_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_item_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_value_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_value_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_value_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='benefit_value_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='cable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='car_insurance_license',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='car_loan_lease_payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='car_repairs_maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='cell_phone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='childcare_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='children_activities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='clothing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='clothing_for_children',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='commissioner_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='condo_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='cpp_contributions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='daycare_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='debt_payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='debts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='dental_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='education',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='ei_premiums',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='ei_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='electricity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='employee_pension_contributions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='entertainment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='eye_care',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='gas_oil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='gifts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='groceries',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='hair_care_beauty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='health_insurance_premiums',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='health_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='heat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='household_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='household_supplies',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='housing_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_commissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_ei',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_employment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_pension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_self_employment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_self_employment_before_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_social_assistance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_spousal_support',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_tax_benefits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_total_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='income_workers_comp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='indian_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='indian_status_docs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='interest_in_business',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='internet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='investments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='last_year_gross_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='laundry_dry_cleaning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='life_insurance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='life_insurance_premiums',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='meals_outside',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='medicine_drugs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='money_owed_to_you',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='net_worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_assets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_expenses_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_expenses_specify',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_expenses_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_income_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='other_possessions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='parking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='pay_cheque_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='pension_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='personal_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='pet_care',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='property_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='property_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='public_transit_taxis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='real_estate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='rent_or_mortgage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='repairs_maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='respondent_fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='respondent_lawyer_fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='rrsp_resp_withdrawals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='savings_plans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_capital_gains',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_capital_losses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_dividends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_other_income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_other_income_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_partnership_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_rental_income_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_rental_income_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_rrif_annuity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_rrsp_withdrawals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_a_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_c_expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_c_my_income_for_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_c_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='schedule_c_total_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='school_fees_supplies',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='social_assistance_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='statement_of_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='summer_camp_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='support_paid_for_other_children',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='sworn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='sworn_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='sworn_province_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='telephone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_debts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_debts_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_value_all_property',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_yearly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='transportation_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='union_dues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='utilities_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='vacations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='vehicles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='workers_comp_stub',
            field=models.BooleanField(default=False),
        ),
    ]
