# Generated by Django 5.2.6 on 2026-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_financialstatement_alcohol_tobacco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonnetfamilyproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonnetfamilyproperty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
