# Generated by Django 5.2.6 on 2026-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_comparisonnetfamilyproperty_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='draft',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
