# Generated by Django 5.2.6 on 2026-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_financialstatement_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form13cfinaltotals',
            options={},
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='applicant_pays_to_respondent_app',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='applicant_pays_to_respondent_resp',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='respondent_pays_to_applicant_app',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='respondent_pays_to_applicant_resp',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total1_valuation_date',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total2_debts_liabilities',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total3_property_on_marriage',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total4_excluded_property',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total5_sum',
        ),
        migrations.RemoveField(
            model_name='form13cfinaltotals',
            name='total6_net_family_property',
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
