# Generated by Django 6.0.3 on 2026-03-29 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_form13cfinaltotals_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=100, unique=True)),
                ('form_display_name', models.CharField(max_length=200)),
                ('price_per_print', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['form_display_name'],
            },
        ),
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)')], max_length=100)),
                ('form_id', models.IntegerField()),
                ('form_identifier', models.CharField(blank=True, max_length=255)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('price_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_billed', models.BooleanField(default=False)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('print_events', models.ManyToManyField(related_name='invoices', to='forms.printevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='printevent',
            index=models.Index(fields=['user', 'printed_at'], name='forms_print_user_id_0833a4_idx'),
        ),
        migrations.AddIndex(
            model_name='printevent',
            index=models.Index(fields=['form_type', 'printed_at'], name='forms_print_form_ty_6a3a38_idx'),
        ),
        migrations.AddIndex(
            model_name='printevent',
            index=models.Index(fields=['is_billed'], name='forms_print_is_bill_b3b9b4_idx'),
        ),
    ]
