# Generated by Django 6.0.3 on 2026-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_billingsetting_printevent_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form131FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('court_file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form 13.1 Financial Statement',
                'verbose_name_plural': 'Form 13.1 Financial Statements',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
