# Generated by Django 6.0.3 on 2026-04-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_form131financialstatement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form131financialstatement',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='form131financialstatement',
            name='draft',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='form_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('financial_statement_131', 'Financial Statement - Property & Support (Form 13.1)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)')], max_length=100),
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable/disable all email notifications')),
                ('email_host', models.CharField(blank=True, help_text='SMTP server hostname', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='SMTP port (usually 587 for TLS, 465 for SSL)')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL connection')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS connection')),
                ('email_host_user', models.CharField(blank=True, help_text='SMTP username', max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP password', max_length=255)),
                ('default_from_email', models.CharField(blank=True, help_text='Default sender email', max_length=255)),
                ('admin_notification_email', models.CharField(blank=True, help_text='Email to receive notifications', max_length=255)),
                ('notify_on_login', models.BooleanField(default=True, help_text='Send notification when users log in')),
                ('notify_on_form_create', models.BooleanField(default=True, help_text='Send notification when forms are created')),
                ('notify_on_form_print', models.BooleanField(default=True, help_text='Send notification when forms are printed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
