# Generated by Django 6.0.3 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_form131financialstatement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netfamilyproperty13bfinaltotals',
            name='equalisation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
