# Generated by Django 6.0.3 on 2026-05-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_netfamilyproperty13bfinaltotals_equalisation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_office_address', models.TextField(blank=True, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_address', models.TextField(blank=True, null=True)),
                ('applicant_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('applicant_lawyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_lawyer_address', models.TextField(blank=True, null=True)),
                ('applicant_lawyer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_lawyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_address', models.TextField(blank=True, null=True)),
                ('respondent_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('respondent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('respondent_lawyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_lawyer_address', models.TextField(blank=True, null=True)),
                ('respondent_lawyer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('respondent_lawyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comparisonnetfamilyproperty',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_net_family_properties', to='forms.casefile'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_statements', to='forms.casefile'),
        ),
        migrations.AddField(
            model_name='form131financialstatement',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_131_financial_statements', to='forms.casefile'),
        ),
        migrations.AddField(
            model_name='netfamilyproperty13b',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_family_property_13b_forms', to='forms.casefile'),
        ),
        migrations.AddField(
            model_name='netfamilypropertystatement',
            name='case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_family_property_statements', to='forms.casefile'),
        ),
    ]
