"""Add valuation_date to CaseFile

Generated by assistant to include valuation date on CaseFile.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_casefile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
