# Generated by Django 6.0.3 on 2026-05-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_add_casefile_valuation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffidavitOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('court_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('court_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('plaintiff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('defendant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('served_name', models.CharField(blank=True, max_length=255, null=True)),
                ('served_date', models.DateField(blank=True, null=True)),
                ('served_at_address', models.CharField(blank=True, max_length=512, null=True)),
                ('served_address_type', models.CharField(blank=True, max_length=255, null=True)),
                ('documents_served', models.TextField(blank=True, null=True)),
                ('service_method', models.CharField(blank=True, max_length=255, null=True)),
                ('service_fax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('substituted_service_details', models.TextField(blank=True, null=True)),
                ('commissioner_municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioner_province', models.CharField(blank=True, max_length=255, null=True)),
                ('sworn_date', models.DateField(blank=True, null=True)),
                ('commissioner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affidavits_of_service', to='forms.casefile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
