# Generated by Django 6.0.3 on 2026-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_affidavitofservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affidavitofservice',
            name='service_method',
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_corporation_attorney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_corporation_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_other_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_person_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_recent_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='address_representative_on_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='corporation_director_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='corporation_director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='personal_service_corporation_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='personal_service_corporation_officer_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='personal_service_other_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='personal_service_other_person_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='personal_service_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='server_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='server_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_by_fax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_fax_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_lawyer_or_paralegal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_place_residence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_place_residence_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_place_residence_registered_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_place_residence_regular_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_registered_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_regular_lettermail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_to_corporation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='substituted_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='substituted_service_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='form_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('financial_statement_131', 'Financial Statement - Property & Support (Form 13.1)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)'), ('affidavit_service', 'Affidavit of Service (Form 6B)')], max_length=100),
        ),
    ]
