# Generated by Django 6.0.3 on 2026-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_remove_affidavitofservice_service_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavitofservice',
            name='form_variant',
            field=models.CharField(choices=[('form_6b', 'Form 6B'), ('form_8a', 'Form 8A')], default='form_6b', max_length=20),
        ),
    ]
