# Generated by Django 6.0.3 on 2026-05-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_affidavitofservice_courier_address_home_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affidavitofservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='affidavitofservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='affidavitofservice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='printevent',
            name='form_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('financial_statement_131', 'Financial Statement - Property & Support (Form 13.1)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)'), ('application_divorce_8a', 'Form 8A — Application (Divorce)'), ('affidavit_service', 'Affidavit of Service (Form 6B)'), ('certificate_of_divorce', 'Certificate of Divorce (Form 36B)')], max_length=100),
        ),
        migrations.CreateModel(
            name='CertificateOfDivorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('court_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_address', models.TextField(blank=True, null=True)),
                ('applicant_lawyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_lawyer_address', models.TextField(blank=True, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_address', models.TextField(blank=True, null=True)),
                ('respondent_lawyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_lawyer_address', models.TextField(blank=True, null=True)),
                ('marriage_place', models.CharField(blank=True, max_length=255, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('divorce_order_date', models.DateField(blank=True, null=True)),
                ('divorce_effective_date', models.DateField(blank=True, null=True)),
                ('date_of_signature', models.DateField(blank=True, null=True)),
                ('clerk_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_of_divorce', to='forms.casefile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
