# Generated by Django 6.0.3 on 2026-05-17 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_alter_affidavitofservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affidavitofservice',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
