# Generated by Django 5.2.14 on 2026-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_fix_divorceorder_softdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorceorder',
            name='persons_in_court',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divorceorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='form_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('financial_statement_131', 'Financial Statement - Property & Support (Form 13.1)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)'), ('application_divorce_8a', 'Form 8A — Application (Divorce)'), ('affidavit_service', 'Affidavit of Service (Form 6B)'), ('certificate_of_divorce', 'Certificate of Divorce (Form 36B)'), ('divorce_order', 'Divorce Order (Form 25A)')], max_length=100),
        ),
    ]
