# Generated by Django 6.0.3 on 2026-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_add_cruelty_victim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavitofservice',
            name='applicant_lawyer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_1_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_2_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_3_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_4_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_5_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='document_5_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='respondent_lawyer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='served_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_document_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_electronic_document_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_fax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_next_day_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_same_day_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affidavitofservice',
            name='service_substituted',
            field=models.BooleanField(default=False),
        ),
    ]
