# Generated by Django 6.0.3 on 2026-05-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_affidavitofservice_applicant_lawyer_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
