# Generated by Django 6.0.3 on 2026-06-05 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_add_divorce_order_a25a'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorceorder',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='applicant_lawyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='applicant_lawyer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='respondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='respondent_lawyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='respondent_lawyer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divorceorder',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='affidavitofservice',
            name='kilometres_travelled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='affidavitofservice',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='affidavitofservice',
            name='travel_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='billingsetting',
            name='price_per_print',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybankaccount',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybankaccount',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybankaccount',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybankaccount',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybusiness',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybusiness',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybusiness',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertybusiness',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyhouseholditem',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyhouseholditem',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyhouseholditem',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyhouseholditem',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyinsurance',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyinsurance',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyinsurance',
            name='face_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyinsurance',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonnetfamilypropertyinsurance',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='divorceordera25a',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='alcohol_tobacco',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='automatic_deductions_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='babysitting_costs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='benefit_value_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='benefit_value_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='benefit_value_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='benefit_value_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='cable',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='car_insurance_license',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='car_loan_lease_payments',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='car_repairs_maintenance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='cell_phone',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='childcare_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='children_activities',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='clothing',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='clothing_for_children',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='condo_fees',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='cpp_contributions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='daycare_expense',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='debt_payments',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='dental_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='education',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='ei_premiums',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='electricity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='employee_pension_contributions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='entertainment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='eye_care',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='gas_oil',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='gifts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='groceries',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='hair_care_beauty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='health_insurance_premiums',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='health_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='heat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='household_contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='household_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='household_supplies',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='housing_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_commissions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_ei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_employment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_investment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_other',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_pension',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_self_employment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_self_employment_before_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_social_assistance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_spousal_support',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_tax_benefits',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_taxes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_total_annual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_total_monthly',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_workers_comp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='internet',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='last_year_gross_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='laundry_dry_cleaning',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='life_insurance_premiums',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='meals_outside',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='medicine_drugs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_worth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='other_expenses_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='other_expenses_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='parking',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='personal_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='pet_care',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='property_insurance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='property_taxes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='public_transit_taxis',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='rent_or_mortgage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='repairs_maintenance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='rrsp_resp_withdrawals',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_capital_gains',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_capital_losses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_dividends',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_other_income_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_partnership_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_rental_income_gross',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_rental_income_net',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_rrif_annuity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_rrsp_withdrawals',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_a_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_c_my_income_for_share',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_c_total_annual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='schedule_c_total_monthly',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='school_fees_supplies',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='spouse_income_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='summer_camp_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='support_paid_for_other_children',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='telephone',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_debts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_debts_outstanding',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_value_all_property',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_yearly_expenses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='transportation_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='union_dues',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='utilities_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='vacations',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13casset',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13casset',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13casset',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13casset',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cbusinessinterest',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cbusinessinterest',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cbusinessinterest',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cbusinessinterest',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cdebtliability',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cdebtliability',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cdebtliability',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cdebtliability',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cexcludedproperty',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cexcludedproperty',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cexcludedproperty',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cexcludedproperty',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_app_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_applicant_pays',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='eq_resp_pos_respondent_pays',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total1_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total2_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total3_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total4_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total5b_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_app_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cfinaltotals',
            name='total6_resp_pos_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cgeneralhouseholditem',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cgeneralhouseholditem',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cgeneralhouseholditem',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cgeneralhouseholditem',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmarriageproperty',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmarriageproperty',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmarriageproperty',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmarriageproperty',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmoneyowed',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmoneyowed',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmoneyowed',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cmoneyowed',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cotherproperty',
            name='applicant_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cotherproperty',
            name='applicant_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cotherproperty',
            name='respondent_position_applicant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='form13cotherproperty',
            name='respondent_position_respondent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13basset',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13basset',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bdebt',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bdebt',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bexcluded',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bexcluded',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bfinaltotals',
            name='total6',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bmarriagedebt',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bmarriagedebt',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bmarriageproperty',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilyproperty13bmarriageproperty',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilypropertyasset',
            name='applicant_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='netfamilypropertyasset',
            name='respondent_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='form_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement (Form 13)'), ('financial_statement_131', 'Financial Statement - Property & Support (Form 13.1)'), ('net_family_property_13b', 'Net Family Property (Form 13B)'), ('comparison_nfp', 'Comparison of Net Family Property (Form 13C)'), ('application_divorce_8a', 'Form 8A — Application (Divorce)'), ('affidavit_service', 'Affidavit of Service (Form 6B)'), ('certificate_of_divorce', 'Certificate of Divorce (Form 36B)'), ('divorce_order', 'Divorce Order (Form 25A)'), ('divorce_order_onepage', 'Divorce Order (one page)'), ('divorce_order_a25a', 'Divorce Order (Form A-25A)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='price_charged',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=30),
        ),
    ]
