# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_divorceorder_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
