# Generated by Django 5.2.14 on 2026-06-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_financialstatement_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='sworn_affidavit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
