from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from decimal import Decimal
from datetime import date

from forms.models import CaseFile, FinancialStatement

User = get_user_model()


def get_or_create_test_user():
    user, created = User.objects.get_or_create(
        username='ui_testuser',
        defaults={
            'email': 'ui_testuser@example.com',
            'is_staff': True,
            'is_active': True,
        }
    )
    if created:
        user.set_password('test123')
        user.save()
    return user


class Command(BaseCommand):
    help = 'Create a complete dummy FinancialStatement for manual UI testing.'

    def handle(self, *args, **options):
        user = get_or_create_test_user()

        case, _ = CaseFile.objects.get_or_create(
            owner=user,
            court_file_number='DUMMY-CASE-001',
            defaults={
                'court_name': 'Ontario Superior Court of Justice',
                'court_office_address': '393 University Avenue, Toronto, ON M5G 1E6',
                'applicant_name': 'Sarah Johnson',
                'respondent_name': 'Michael Johnson',
            }
        )

        statement = FinancialStatement.objects.create(
            case_file=case,
            court_name='Ontario Superior Court of Justice',
            court_file_number='DUMMY-FS-2026-001',
            court_office_address='393 University Avenue, Toronto, ON M5G 1E6',
            prepared_by='applicant',
            applicant_name='Sarah Johnson',
            applicant_address='123 Main Street, Toronto, ON M5H 2R2',
            applicant_phone='416-555-0123',
            applicant_fax='416-555-0124',
            applicant_email='sarah.johnson@example.com',
            applicant_lawyer_name='John Smith',
            applicant_lawyer_address='456 Bay Street, Toronto, ON M5J 2R2',
            applicant_lawyer_phone='416-555-5555',
            applicant_lawyer_fax='416-555-5556',
            applicant_lawyer_email='john.smith@lawfirm.ca',
            respondent_name='Michael Johnson',
            respondent_address='789 King Street West, Toronto, ON M5H 2Y9',
            respondent_phone='416-555-9999',
            respondent_fax='416-555-9998',
            respondent_email='michael.johnson@example.com',
            respondent_lawyer_name='Jane Doe',
            respondent_lawyer_address='321 Church Street, Toronto, ON M5B 1Y7',
            respondent_lawyer_phone='416-555-7777',
            respondent_lawyer_fax='416-555-7778',
            respondent_lawyer_email='jane.doe@lawfirm.ca',
            my_name='Sarah Johnson',
            my_location='Toronto, Ontario',
            sworn_affidavit='I solemnly swear/affirm that the contents of this Financial Statement are true.',
            is_employed=True,
            employer_name_address='ABC Corporation, 100 Front Street, Toronto, ON',
            is_self_employed=False,
            business_name_address='',
            is_unemployed=False,
            unemployed_since=None,
            pay_cheque_stub=True,
            social_assistance_stub=False,
            pension_stub=False,
            workers_comp_stub=False,
            ei_stub=False,
            statement_of_income=False,
            other_income_proof=True,
            last_year_gross_income=Decimal('85000.00'),
            indian_status=False,
            indian_status_docs='',
            income_employment=Decimal('7000.00'),
            income_commissions=Decimal('250.00'),
            income_self_employment_before_expenses=Decimal('0.00'),
            income_self_employment=Decimal('0.00'),
            income_ei=Decimal('0.00'),
            income_workers_comp=Decimal('0.00'),
            income_social_assistance=Decimal('0.00'),
            income_investment=Decimal('150.00'),
            income_pension=Decimal('0.00'),
            income_spousal_support=Decimal('0.00'),
            income_tax_benefits=Decimal('200.00'),
            income_other=Decimal('0.00'),
            income_total_monthly=Decimal('7350.00'),
            income_total_annual=Decimal('88200.00'),
            benefit_item_1='Investment income',
            benefit_details_1='Dividend income from investment account',
            benefit_value_1=Decimal('150.00'),
            benefit_item_2='Tax credits',
            benefit_details_2='GST/HST credit and provincial benefit',
            benefit_value_2=Decimal('200.00'),
            benefit_item_3='Employer allowance',
            benefit_details_3='Cell phone and home office allowance',
            benefit_value_3=Decimal('100.00'),
            benefit_item_4='',
            benefit_details_4='',
            benefit_value_4=Decimal('0.00'),
            cpp_contributions=Decimal('300.00'),
            ei_premiums=Decimal('80.00'),
            income_taxes=Decimal('1800.00'),
            employee_pension_contributions=Decimal('250.00'),
            union_dues=Decimal('0.00'),
            automatic_deductions_subtotal=Decimal('2430.00'),
            rent_or_mortgage=Decimal('2100.00'),
            property_taxes=Decimal('150.00'),
            property_insurance=Decimal('75.00'),
            condo_fees=Decimal('325.00'),
            repairs_maintenance=Decimal('100.00'),
            housing_subtotal=Decimal('2750.00'),
            water=Decimal('0.00'),
            heat=Decimal('0.00'),
            electricity=Decimal('120.00'),
            telephone=Decimal('45.00'),
            cell_phone=Decimal('100.00'),
            cable=Decimal('90.00'),
            internet=Decimal('85.00'),
            utilities_subtotal=Decimal('440.00'),
            public_transit_taxis=Decimal('150.00'),
            gas_oil=Decimal('220.00'),
            car_insurance_license=Decimal('180.00'),
            car_repairs_maintenance=Decimal('90.00'),
            parking=Decimal('120.00'),
            car_loan_lease_payments=Decimal('400.00'),
            transportation_subtotal=Decimal('1160.00'),
            health_insurance_premiums=Decimal('90.00'),
            dental_expenses=Decimal('45.00'),
            medicine_drugs=Decimal('60.00'),
            eye_care=Decimal('25.00'),
            health_subtotal=Decimal('220.00'),
            clothing=Decimal('150.00'),
            hair_care_beauty=Decimal('60.00'),
            alcohol_tobacco=Decimal('50.00'),
            education=Decimal('0.00'),
            entertainment=Decimal('200.00'),
            gifts=Decimal('75.00'),
            personal_subtotal=Decimal('535.00'),
            groceries=Decimal('650.00'),
            household_supplies=Decimal('90.00'),
            meals_outside=Decimal('240.00'),
            pet_care=Decimal('80.00'),
            laundry_dry_cleaning=Decimal('40.00'),
            household_subtotal=Decimal('1100.00'),
            daycare_expense=Decimal('0.00'),
            babysitting_costs=Decimal('150.00'),
            childcare_subtotal=Decimal('150.00'),
            life_insurance_premiums=Decimal('90.00'),
            rrsp_resp_withdrawals=Decimal('0.00'),
            vacations=Decimal('225.00'),
            school_fees_supplies=Decimal('85.00'),
            clothing_for_children=Decimal('95.00'),
            children_activities=Decimal('180.00'),
            summer_camp_expenses=Decimal('75.00'),
            debt_payments=Decimal('325.00'),
            support_paid_for_other_children=Decimal('0.00'),
            other_expenses_specify='Gym membership and streaming subscriptions',
            other_expenses_amount=Decimal('120.00'),
            other_expenses_subtotal=Decimal('120.00'),
            total_monthly_expenses=Decimal('8575.00'),
            total_yearly_expenses=Decimal('102900.00'),
            real_estate=[
                {'description': 'Principal residence, 123 Main Street, Toronto, ON', 'value': '900000.00'},
                {'description': 'Vacation condo, Muskoka, ON', 'value': '420000.00'},
            ],
            vehicles=[
                {'description': '2020 Honda Accord', 'value': '18000.00'},
                {'description': '2018 Toyota RAV4', 'value': '22000.00'},
            ],
            other_possessions=[
                {'description': 'Jewellery and fine art', 'value': '28000.00'},
            ],
            investments=[
                {'description': 'RRSP - Scotia', 'value': '65000.00'},
                {'description': 'TFSA - RBC', 'value': '42000.00'},
            ],
            bank_accounts=[
                {'description': 'RBC chequing account', 'value': '5500.00'},
                {'description': 'TD savings account', 'value': '16000.00'},
            ],
            savings_plans=[
                {'description': 'Employer pension plan', 'value': '125000.00'},
            ],
            life_insurance=[
                {'description': 'Sun Life term life insurance', 'value': '0.00'},
            ],
            interest_in_business=[
                {'description': '25% ownership of ABC Consulting Inc.', 'value': '45000.00'},
            ],
            money_owed_to_you=[
                {'description': 'Loan to sibling', 'value': '5000.00'},
            ],
            other_assets=[
                {'description': 'Loyalty points and travel credits', 'value': '2000.00'},
            ],
            total_value_all_property=Decimal('1536500.00'),
            debts={
                'mortgage_creditor_1': 'RBC Mortgage',
                'mortgage_amount_1': '450000.00',
                'mortgage_monthly_1': '2100.00',
                'mortgage_payment_1': 'yes',
                'other_debt_creditor_1': 'Scotiabank Line of Credit',
                'other_debt_amount_1': '25000.00',
                'other_debt_monthly_1': '300.00',
                'other_debt_payment_1': 'yes',
                'credit_card_creditor_1': 'Visa Card',
                'credit_card_amount_1': '3200.00',
                'credit_card_monthly_1': '120.00',
                'credit_card_payment_1': 'yes',
                'credit_card_creditor_2': 'Mastercard',
                'credit_card_amount_2': '2100.00',
                'credit_card_monthly_2': '90.00',
                'credit_card_payment_2': 'yes',
            },
            total_debts_outstanding=Decimal('480400.00'),
            total_assets=Decimal('1536500.00'),
            total_debts=Decimal('480400.00'),
            net_worth=Decimal('1056100.00'),
            sworn_municipality='Toronto',
            sworn_province_country='Ontario, Canada',
            sworn_date=date.today(),
            signature='Sarah Johnson',
            commissioner_signature='Mary Smith, Commissioner for Taking Affidavits',
            schedule_a_partnership_income=Decimal('0.00'),
            schedule_a_rental_income_gross=Decimal('0.00'),
            schedule_a_rental_income_net=Decimal('0.00'),
            schedule_a_dividends=Decimal('0.00'),
            schedule_a_capital_gains=Decimal('0.00'),
            schedule_a_capital_losses=Decimal('0.00'),
            schedule_a_rrsp_withdrawals=Decimal('0.00'),
            schedule_a_rrif_annuity=Decimal('0.00'),
            schedule_a_other_income_source='Other investment income',
            schedule_a_other_income_amount=Decimal('150.00'),
            schedule_a_subtotal=Decimal('150.00'),
            lives_alone=False,
            living_with_someone=True,
            living_with_name='Michael Johnson',
            lives_with_other_adults=False,
            other_adults_names='',
            has_children_in_home=False,
            number_of_children_in_home=0,
            spouse_works=True,
            spouse_work_place='XYZ Corporation',
            spouse_does_not_work=False,
            spouse_earns_income=True,
            spouse_income_amount=Decimal('2500.00'),
            spouse_income_period='monthly',
            spouse_no_income=False,
            household_contribution=True,
            household_contribution_amount=Decimal('500.00'),
            household_contribution_period='monthly',
            schedule_c_expenses=[
                {'child_name': 'Emma Johnson', 'expense': 'Music lessons', 'amount_per_year': '1200.00', 'tax_credits': '0.00'},
                {'child_name': 'Emma Johnson', 'expense': 'Sports registration', 'amount_per_year': '800.00', 'tax_credits': '0.00'},
            ],
            schedule_c_total_annual=Decimal('2000.00'),
            schedule_c_total_monthly=Decimal('166.67'),
            schedule_c_my_income_for_share=Decimal('7350.00'),
        )

        self.stdout.write(self.style.SUCCESS(f'Created dummy FinancialStatement #{statement.id}'))
        self.stdout.write('Login user: ui_testuser')
        self.stdout.write('Password: test123')
        self.stdout.write('Case ID: {}'.format(case.id))
        self.stdout.write('FinancialStatement ID: {}'.format(statement.id))
        self.stdout.write('Run: python manage.py populate_financial_statement_dummy')
