from django.urls import path
from . import views

urlpatterns = [
    path('financial-statement/list/', views.financial_statement_list, name='financial_statement_list'),
    path('financial-statement/delete/<int:pk>/', views.financial_statement_delete, name='financial_statement_delete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('comparison-nfp/', views.ComparisonNetFamilyPropertyListView.as_view(), name='comparison_nfp_list'),
    path('comparison-nfp/<int:pk>/', views.ComparisonNetFamilyPropertyDetailView.as_view(), name='comparison_nfp_detail'),
    path('comparison-nfp/delete/<int:pk>/', views.comparison_nfp_delete, name='comparison_nfp_delete'),
    path('comparison-nfp/new/', views.comparison_nfp_create, name='comparison_nfp_create'),
    path('comparison-nfp/success/', views.comparison_nfp_success, name='comparison_nfp_success'),
    path('net-family-property/', views.net_family_property_create, name='net_family_property_create'),
    path('financial-statement/', views.financial_statement_create, name='financial_statement_create'),
    # 13B Multi-page form
    path('net-family-property-13b/', views.net_family_property_13b_create_page1, name='net_family_property_13b_page1'),
    path('net-family-property-13b/<int:pk>/', views.net_family_property_13b_create_page1, name='net_family_property_13b_page1_edit'),
    path('net-family-property-13b/<int:pk>/page2/', views.net_family_property_13b_create_page2, name='net_family_property_13b_page2'),
    path('net-family-property-13b/<int:pk>/page3/', views.net_family_property_13b_create_page3, name='net_family_property_13b_page3'),
    path('net-family-property-13b/list/', views.net_family_property_13b_list, name='net_family_property_13b_list'),
    path('net-family-property-13b/delete/<int:pk>/', views.net_family_property_13b_delete, name='net_family_property_13b_delete'),
    path('net-family-property-13b/view/<int:pk>/', views.net_family_property_13b_view, name='net_family_property_13b_view'),
    path('net-family-property-13b/print/<int:pk>/', views.net_family_property_13b_print, name='net_family_property_13b_print'),
    # Recycle Bin
    path('recycle-bin/', views.recycle_bin, name='recycle_bin'),
    path('recycle-bin/restore/<str:form_type>/<int:pk>/', views.restore_form, name='restore_form'),
    path('recycle-bin/permanent-delete/<str:form_type>/<int:pk>/', views.permanent_delete, name='permanent_delete'),
    path('recycle-bin/empty/', views.empty_recycle_bin, name='empty_recycle_bin'),
    # Comparison NFP pages
    path('comparison-nfp/page1/<int:pk>/', views.comparison_nfp_page1, name='comparison_nfp_page1_edit'),
    path('comparison-nfp/page2/<int:pk>/', views.comparison_nfp_page2, name='comparison_nfp_page2'),
    path('comparison-nfp/page3/<int:pk>/', views.comparison_nfp_page3, name='comparison_nfp_page3'),
    path('comparison-nfp/page4/<int:pk>/', views.comparison_nfp_page4, name='comparison_nfp_page4'),
    path('comparison-nfp/page5/<int:pk>/', views.comparison_nfp_page5, name='comparison_nfp_page5'),
    path('comparison-nfp/<int:pk>/draft/', views.comparison_nfp_draft, name='comparison_nfp_draft'),
    path('comparison-nfp/print/<int:pk>/', views.comparison_nfp_print, name='comparison_nfp_print'),
    path('comparison-nfp/view/<int:pk>/', views.comparison_nfp_full_view, name='comparison_nfp_full_view'),
    path('financial-statement/page1/', views.financial_statement_page1_redirect, name='financial_statement_page1_redirect'),
    path('financial-statement/new/', views.financial_statement_page1_new, name='financial_statement_page1_new'),
    path('financial-statement/<int:pk>/edit/', views.financial_statement_page1, name='financial_statement_page1_edit'),
    path('financial-statement/page1/<int:pk>/', views.financial_statement_page1, name='financial_statement_page1'),
    path('financial-statement/page2/<int:pk>/', views.financial_statement_page2, name='financial_statement_page2'),
    path('financial-statement/page3/<int:pk>/', views.financial_statement_page3, name='financial_statement_page3'),
    path('financial-statement/page4/<int:pk>/', views.financial_statement_page4, name='financial_statement_page4'),
    path('financial-statement/page5/<int:pk>/', views.financial_statement_page5, name='financial_statement_page5'),
    path('financial-statement/page6/<int:pk>/', views.financial_statement_page6, name='financial_statement_page6'),
    path('financial-statement/page7/<int:pk>/', views.financial_statement_page7, name='financial_statement_page7'),
    path('financial-statement/page8/<int:pk>/', views.financial_statement_page8, name='financial_statement_page8'),
    path('financial-statement/view/<int:pk>/', views.financial_statement_view, name='financial_statement_view'),
    path('financial-statement/print/<int:pk>/', views.financial_statement_print, name='financial_statement_print'),
    # Billing & Print Tracking
    path('billing/', views.billing_dashboard, name='billing_dashboard'),
    path('billing/history/', views.billing_history, name='billing_history'),
    path('billing/history/delete/<int:pk>/', views.delete_print_event, name='delete_print_event'),
    path('billing/settings/', views.billing_settings_view, name='billing_settings'),
    path('billing/admin-report/', views.admin_billing_report, name='admin_billing_report'),
]
